### ISSUE TITLE
FINAL Rules of Evolutionary Forest

### ISSUE THREAD

**Issue by MohammadSoltani100** [hengzhe-zhang/EvolutionaryForest#74]
* Evolutionary Forest version:
* Python version:3.8
* Operating System:

### Description

How can I print final expression of Evolutionary Forest (if any) like PSTree or gplearn?

Thanks in advance

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by hengzhe-zhang** [comment]
Hi! Thanks for your interest in this package. It is possible to visualize the final result by printing all GP individuals in the hall-of-fame. However, a better way might be to only visualize important features because Evolutionary Forest may contain hundreds of high-order features. To visualize important features, please refer to [a tutorial.](https://github.com/hengzhe-zhang/EvolutionaryForest/blob/master/tutorial/diabetes_regression.ipynb)

**Comment by MohammadSoltani100** [comment]
Hello dear Hengzhe Zhang

Thank you so much for the strong package and your  kind reply. In fact, my
goal is to model a hydrological process, in which both 'important
features', and  final 'if-then rule' are important.
For your information, I want to use both "PSTree" and "Evolutionary Forest"
for my purpose. my question is how can I reveal the final expression
(script)?
Thank you very much for your valuable work.
best regards

**Comment by hengzhe-zhang** [comment]
Hi @MohammadSoltani100 ! Here is a way to print the final expression. However, the final decision tree might be large and unexplainable. A more advanced approach for interpretable-ML is still under-developed.

```py3
for id, h in enumerate(regr.hof):
    print('Tree', id)
    print('GP Features', h)
    print(tree.export_text(h.pipe['Ridge']))
```

**Comment by MohammadSoltani100** [comment]
You are right
Wait for that
Thanks a lot.
