### ISSUE TITLE
Catboost Error

### ISSUE THREAD

**Issue by ericborgos** [hengzhe-zhang/EvolutionaryForest#89]
FYI, you left CatBoost off of your requirements.txt file, so it then gives an error trying to import it.

**Comment by hengzhe-zhang** [comment]
Thank you. It may be because I imported the CatBoost encoder into the legacy code. I am considering whether to remove some encoders that require third-party libraries because users can easily preprocess data using these libraries.

Also, if I remember correctly, CatBoost is very difficult to install on ARM servers. If this hinders you, please tell me and I will address this issue as soon as possible.

**Comment by ericborgos** [comment]
I am using Google Colab so adding CatBoost to requirements.txt worked fine. But, after that, I had another error ( "ImportError: cannot import name '_check_fit_params' from 'sklearn.utils.validation' (/usr/lo" ) in Colab, but changing requirements.txt to scikit_learn==1.2.2 fixed that.
